### ISSUE TITLE
Contenuti sito: quali sono e con che ordinamento?

### ISSUE THREAD

**Issue by nelsonmau** [ondata/premio-tesi-ondata#1]

**Comment by aborruso** [comment]
che sono i soli?

**Comment by nelsonmau** [comment]
qui il regolamento https://docs.google.com/document/d/1h2I45pB0Z8Gu-vqP1K0BUIZ3V9vjuKGx3wOltawV3bA/edit#

**Comment by nelsonmau** [comment]
qui il form provvisorio, per ora sembra accessibile solo da utenti ondata https://docs.google.com/a/ondata.it/forms/d/e/1FAIpQLSdNlaLbX0O9ZbzNFugrnEBtOeNbSbA2k3FropqH1Ktsc33AIQ/viewform

**Comment by nelsonmau** [comment]
issue ridondante, chiudo qui :-)
