### ISSUE TITLE
Link al bando del concorso nella dichiarazione in fondo alla pagina

### ISSUE THREAD

**Issue by dataibi** [ondata/premio-tesi-ondata#10]
Nella Dichiarazione per il trattamento dei dati personali il candidato dichiara di aver preso visione del bando di concorso (disponibile qui https://goo.gl/P2DQ2c). Se possibile il testo del link potrebbe essere un link vero e proprio.

**Comment by nelsonmau** [comment]
eh no, è imposibile per colpa del plugin purtroppo...
