### ISSUE TITLE
Errore 500 dopo l'invio del form

### ISSUE THREAD

**Issue by nelsonmau** [ondata/premio-tesi-ondata#12]
ora genera questo problema.
Per riprodurre il problema:
1) compilare per bene il form
2) inviarlo

**Nota**: nonostante il sistema restituisca errore, in realtà l'entry del form viene correttamente memorizzata
Quello che non funziona:
1) l'utente non riceve la notifica via mail
2) dopo l'invio il sistema risponde "Errore 500"

L'unica modifica che ho fatto rispetto a prima è l'attivazione delle notifiche mail per chi compila il form. È possibile che

**Comment by nelsonmau** [comment]
@jenkin e @aborruso fate un check please

**Comment by nelsonmau** [comment]
funziona, stavolta l'eroe è stato il cimarello! @jenkin 1 - @aborruso 1

**Comment by aborruso** [comment]
ma io non c'ero nemmeno :(

Mica ho scritto si potrà fare, bla, bla, bla

**Comment by nelsonmau** [comment]
@aborruso è un goal in contropiede, per onorare l'ultimo match di totti
