### ISSUE TITLE
Elementi svg nella frontpage come immagini separate

### ISSUE THREAD

**Issue by jenkin** [ondata/premio-tesi-ondata#17]
Perché mettere l'svg in linea? I vari elementi sono già presenti nella cartella img/, non possono semplicemente essere inclusi con il [tag img](https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_as_an_Image)?

**Comment by Jaaapiii** [comment]
Assolutamente sì! In questo caso non c'è motivo di metterli in linea, l'ho fatto per "abitudine" poichè mettendoli in linea puoi gestire l'svg direttamente da css (es. cambiare colore, effetti, animazioni e cose così), mentre inserendoli come "img" no. Ho caricato l'svg comunque nella cartella così la cartella di progetto è completa di tutte le risorse.

Ci sono per caso dei problemi di performance per cui è meglio evitare?

**Comment by jenkin** [comment]
No, in realtà è che se lo stesso elemento appare in più template di pagina, meglio averlo come immagine separata. Ma forse nemmeno serve, quindi per ora lasciamo così... :)

**Comment by Jaaapiii** [comment]
ok! allora chiudo issue
