### ISSUE TITLE
Porting su wordpress

### ISSUE THREAD

**Issue by jenkin** [ondata/premio-tesi-ondata#18]
L'homepage si integra perfettamente con il tema, rimane da decidere il template delle pagine interne, come per esempio quella del form. Propongo di mantenere solo un semplice header come questo screenshot in allegato.

![screenshot_20170609_095132](https://user-images.githubusercontent.com/426495/26966202-6c605a90-4cf9-11e7-9fa3-849dd8a122d2.png)

**Comment by Jaaapiii** [comment]
per me può andare bene, devo prepararti qualcosa?

**Comment by jenkin** [comment]
Se vuoi farmi qui un file `page.html` con quell'header, poi copio incollo nel template di pagina di wordpress... :)

**Comment by jenkin** [comment]
Ok, ho fatto al volo...
