### ISSUE TITLE
Layout sito

### ISSUE THREAD

**Issue by nelsonmau** [ondata/premio-tesi-ondata#2]
direi onepage, @japisolmi tirerà fuori qualche tema bootstrap dal cilindro?

**Comment by nelsonmau** [comment]
@Japisolmi riesci a darmi un feedback finale in settimana? se no faccio io se sei incasinato dai

**Comment by Jaaapiii** [comment]
yes! lunedì mattina o un giorno della settimana prossima quando vuoi vediamoci che lo montiamo insieme :)

**Comment by Jaaapiii** [comment]
Siamo a buon punto, è funzionante ma senza contenuti e con qualche micro bug da mobile. Se vi andasse di testarlo e aprirmi issue sui bug rimasti sarei felice :)

**Comment by nelsonmau** [comment]
ho messo i testi!
