### ISSUE TITLE
Form per i candidati

### ISSUE THREAD

**Issue by nelsonmau** [ondata/premio-tesi-ondata#4]
al momento è qui
https://docs.google.com/a/ondata.it/forms/d/e/1FAIpQLSdNlaLbX0O9ZbzNFugrnEBtOeNbSbA2k3FropqH1Ktsc33AIQ/viewform

ma c'è un limite ai soli membri di Ondata per l'upload, serve una alternativa

**Comment by Jaaapiii** [comment]
dai un occhio qui https://www.smartsurvey.co.uk/pricing

o più in generale qui https://alternativeto.net/software/google-forms/

**Comment by nelsonmau** [comment]
@Japisolmi in generale tutta la parte upload è a pagamento

Guardavo anche plugin wordpress, a pagamento come
https://it.wordpress.org/plugins/form-maker/
e https://it.wordpress.org/plugins/ninja-forms/
e https://it.wordpress.org/plugins/formidable/

**Comment by nelsonmau** [comment]
questo sembra avere gli upload free
https://it.wordpress.org/plugins/captainform/
lo provo

**Comment by nelsonmau** [comment]
stokatz, non possiamo usarlo :(

```
As a WordPress Multisite user, you can only purchase our Hero plan, which provides multisite support.
```

**Comment by aborruso** [comment]
@nelsonmau se WP deve essere, puoi installare sul server, in via del tutto eccezionale :) , anche un WP normale (non Multisite).

**Comment by nelsonmau** [comment]
@aborruso non posso, @jenkin mi ha detto che appena entro sul server devo scrivere subito `su trasparico` sennò rompo tutto

`Aderisci anche tu alla campagna #IoNonInstallo`

**Comment by aborruso** [comment]
@nelsonmau allora valuterei una cosa banale: facciamo finta di lanciare domani il contest, che rimane aperto ad esempio sino a fine novembre.
Nel regolamento scriviamo che apriamo il submitting dal 1 novembre per un mese, e si paga un mese di typeform (o jotform, o sticatz) e passa la malattia.

baci

**Comment by aborruso** [comment]
@nelsonmau l'ho scritta male e l'ho appena modificata.

**Comment by nelsonmau** [comment]
anche surveymonkey, surveymoz etc...
tutti con file upload a pagamento

**Comment by nelsonmau** [comment]
questo sembra funzionare https://www.cognitoforms.com/Ondata1/PartecipaAlPremioOndataInviaLaTuaTesiSuiDatiPubblici

**Comment by dtaibi** [comment]
Ma perché non usare un plugin di wp, es. visual form builder? 

  Davide

**Comment by nelsonmau** [comment]
@dtaibi perché hanno l'opzione "upload" sono nella versione pro a pagamento. Questo che dici tu lo provo subito e torno qui

**Comment by nelsonmau** [comment]
@dtaibi ottimo! FUNZIONA! Usiamo questo e amen, non è necessario neanche essere loggati su wordpress

un esempio di prova qui http://blog.ondata.it/premio-tesi-invia-la-tua-candidatura/

@Japisolmi @aborruso

**Comment by nelsonmau** [comment]
@dtaibi ecco il form, please verifica che ci sia tutto e compilalo per testare http://wp.ondata.it/premiotesi/partecipa/

grazie!

**Comment by lorenzoperone** [comment]
Ciao,
ho testato il formo inserendo degli allegati.
Secondo me il formato della data, se possibile, andrebbe definito come DD/MM/YYYY attualmente è MM/DD/YYYY e può confondere. In via subordinata metterei una nota.
Lorenzo

**Comment by nelsonmau** [comment]
yes, ho cambiato e ora è così `dd/mm/yyyy`

p.s.: vedo la tua entry inviata correttamente, sembra funzionare tutto bene

**Comment by nelsonmau** [comment]
@Japisolmi @aborruso e @dtaibi entro domenica pls provate a compilare il form? http://wp.ondata.it/premiotesi/partecipa/ (no fotoporno please) ;)

**Comment by aborruso** [comment]
Io ho fatto e scritto due issue!

**Comment by dataibi** [comment]
Fatto!

**Comment by nelsonmau** [comment]
funzia tutti tranne un bug: chiudo qui e teniamo le altre issue
