### ISSUE TITLE
Creare dominio di terzo livello: premio.ondata.it

### ISSUE THREAD

**Issue by nelsonmau** [ondata/premio-tesi-ondata#6]
il dominio punta su http://wp.ondata.it/premiotesi/

**Comment by aborruso** [comment]
il puntamento lato gestione DNS è stato fatto: [premio.ondata.it](http://premio.ondata.it).
Ho aggiunto nel DNS:

    premio		A	138.201.249.135

Lato apache ci pensi tu @jenkin ?

Grazie

**Comment by nelsonmau** [comment]
@jenkin move your booty!

**Comment by jenkin** [comment]
Fatto: http://premio.ondata.it/.
