### ISSUE TITLE
l'input form del calendario produce una data errata

### ISSUE THREAD

**Issue by aborruso** [ondata/premio-tesi-ondata#7]
due volte l'anno

![image](https://cloud.githubusercontent.com/assets/30607/26212471/f59ad502-3bf5-11e7-830c-8f208344f1ac.png)

**Comment by dataibi** [comment]
Si verifica sia nel calendario della data di nascita che in quello della data di laurea

**Comment by nelsonmau** [comment]
si era errore mio, avevo messo yyyy invece di yy
(perché ho studiato il pho al CEPU con lo sconto)

ora funzia
