### ISSUE TITLE
localizzare ove possibile in italiano

### ISSUE THREAD

**Issue by aborruso** [ondata/premio-tesi-ondata#8]
![image](https://cloud.githubusercontent.com/assets/30607/26212626/72ace29c-3bf6-11e7-99db-607d6f7da039.png)

**Comment by dataibi** [comment]
Anche 
![schermata 2017-05-19 alle 00 00 28](https://cloud.githubusercontent.com/assets/15361890/26225196/46cdf4ce-3c26-11e7-8ecb-69b9c7425463.png)

**Comment by nelsonmau** [comment]
ora ho fatto il massimo, non ci sono altre opzioni che li possono localizzare

grazie!
