### ISSUE TITLE
l'invio del form dovrebbe produrre una qualche conferma

### ISSUE THREAD

**Issue by aborruso** [ondata/premio-tesi-ondata#9]
Oltre quello a video, almeno un'email con messaggio di conferma dovrebbe essere spedito al mittente

**Comment by nelsonmau** [comment]
l'ho attivata ora, da testare se funzia....

**Comment by nelsonmau** [comment]
probabilmente c'è un bug connesso a #12

**Comment by nelsonmau** [comment]
funziona tutto: via conferma a video (sul sito) che via mail

chiudo qui!
